### ISSUE TITLE
Problème avec l'affichage des résultats de Paris

### ISSUE THREAD

**Issue by jer-em** [bugsounet/MMM-AirParif#1]
Bonjour, 

Un problème semble apparaitre lors de ma sélection de la ville de Paris via le module. 
En effet, les résultats pour Paris n'apparaissent pas sur le miroir (si aucune autre ville sélectionné : "ERREUR : AUCUNE DONNÉE").

> Configuration: 
<img width="471" alt="Bug_Air_Parif" src="https://user-images.githubusercontent.com/61385457/77356570-de200480-6d46-11ea-91b9-993076763fd9.PNG">

> Resultat:
<img width="347" alt="Bug_Air_Parif" src="https://user-images.githubusercontent.com/61385457/77356124-052a0680-6d46-11ea-81d3-2c0c8df25ceb.PNG">

>Erreur possible : Paris possède plusieurs codes postaux (75001 --> 75020), ce qui peut peut-être poser problème lors de la récupération des données ?!
<img width="546" alt="Bug_Air_Parif3" src="https://user-images.githubusercontent.com/61385457/77356489-b2048380-6d46-11ea-8138-80e0d5f1bc28.PNG">

Merci.

**Comment by Maquesi** [comment]
Bonjour, oui je confirme avoir le même problème.
ça fonctionne sans problème avec Massy 91300.

Apparemment AirParif utilise le code INSEE et non pas code postal.
Par exemple pour le 1er arrondissement ce n'est pas 75001 mais 75101.
J'ai testé avec l'API html de AirParif, cela fonctionne bien avec 75101.

Mais ni l'un ni l'autre ne fonctionne ici :(
Peut être le nom de la ville à préciser avec l'arrondissement inclus?

**Comment by bugsounet** [comment]
désolé du retard, j'ai pas tester.
Je vais regarder demain :)

Merci pour vos remontés

**Comment by bugsounet** [comment]
c'est fixé, l'api gouv.fr ne donne pas les bonnes info pour le departement 75 (paris)
j'ai donc forcé d'une autre maniere.

Vous pouvez mettre l'orthographe que vous voulez pour Paris
exemple :  
ville: ["75011,Paris 11ème", "75001,Paris 1er", "75002,Paris"]
ou
ville: ["75101,Paris"]

**Ceci est valable uniquement pour les codes postaux de Paris**

pour mettre a jour le module:
```sh
cd ~/MagicMirror/modules/MMM-AirParif
git pull
```
redémarrer ensuite l'application

Dans l'attente de vos retours,
Cédric

**Comment by jer-em** [comment]
Bonjour, 
Merci pour le change, cela fonctionne ! 
Jer-em
